name: Sultan-Supreme-Strike-V104

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Execute Sultan Strike
        run: |
          # Agar file na ho toh error na aaye isliye touch
          touch target.txt
          python3 attack.py $(cat target.txt)
